[server]
fileWatcherType = "none"
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1EB182"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F2B"
textColor = "#FAFAFA"
font = "sans serif"
